// Generates src/environments/version.ts at build/serve time so the deployed
// app can report exactly which build is live. Regenerated by the prebuild /
// prestart / postinstall npm hooks — the output file is git-ignored.
//
// Sources, in order of preference:
//   version   -> package.json "version"
//   commit    -> VERCEL_GIT_COMMIT_SHA / GITHUB_SHA env, else `git rev-parse`
//   commitUrl -> Vercel repo env, else the `origin` GitHub remote
//   buildTime -> now (ISO)
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sh = (cmd) => {
  try {
    return execSync(cmd, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return '';
  }
};

const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const version = pkg.version || '0.0.0';

const fullSha = process.env.VERCEL_GIT_COMMIT_SHA || process.env.GITHUB_SHA || sh('git rev-parse HEAD');
const commit = fullSha ? fullSha.slice(0, 7) : 'local';

let repoUrl = '';
const { VERCEL_GIT_REPO_OWNER: owner, VERCEL_GIT_REPO_SLUG: slug } = process.env;
if (owner && slug) {
  repoUrl = `https://github.com/${owner}/${slug}`;
} else {
  const m = sh('git remote get-url origin').match(/github\.com[:/](.+?)(?:\.git)?$/);
  if (m) repoUrl = `https://github.com/${m[1]}`;
}
const commitUrl = repoUrl && fullSha ? `${repoUrl}/commit/${fullSha}` : '';

const buildTime = new Date().toISOString();
const buildDate = buildTime.slice(0, 10);

const body = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit, do not commit.
// Regenerated on every install, serve (prestart) and build (prebuild).
export const APP_VERSION = {
  version: '${version}',
  commit: '${commit}',
  commitUrl: '${commitUrl}',
  buildDate: '${buildDate}',
  buildTime: '${buildTime}',
} as const;
`;

const target = resolve(root, 'src/environments/version.ts');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, body);
console.log(`[version] ${version} (${commit}) ${buildDate}`);
